# -*- coding: utf-8 -*-
"""index

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWRQbp8jWBVK_ezjF7g9EDJpwimgadGa
"""

import streamlit as st

# ⚠️ Deve ser o primeiro comando depois das importações!
st.set_page_config(layout="wide")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

# Importar suas outras funções/módulos
import globals
import graficos


st.set_page_config(layout='wide',
                   page_title='Datathon Passos Mágicos - FIAP')

col1, col2,col3, col4 = st.columns(4, gap='small', vertical_alignment='center', border=False)

with col2:
    st.image('assets/images/fiap.png', width=160, clamp=True)

with col3:
    st.image('assets/images/passos_magicos.png', width=200, clamp=True)

pages = [
        st.Page(page="Pages/introducao.py", title="Introdução", default=True),
        st.Page(page="Pages/analysis.py", title="Análise", default=False),
        st.Page(page="Pages/model.py", title="Modelo", default=False),
        st.Page(page="Pages/Dashboard.py", title="Dashboard", default=False),
        st.Page(page="Pages/Ferramentas.py", title="Ferramentas", default=False),
        st.Page(page="Pages/dicionario.py", title="Dicionario", default=False),
        st.Page(page="Pages/conclusao.py", title="Conclusão", default=False),
]

with st.sidebar:
    st.subheader('Autores')
    st.markdown(""" RM355794 - Beatriz Sisa Severino """)
    st.markdown(""" RM355581 - Bruna Frutuoso Cavalheiro """)
    st.markdown(""" RM355497 - Michael Jourdain Gbedjinou """)

    st.divider()

    st.subheader("Instalando as dependências do app localmente")
    st.code(body="python -m venv venv", language="shell")
    st.code(body="python venv/Scripts/activate", language="shell")
    st.code(body="pip install -r requirements.txt", language="shell")

    st.divider()

    st.subheader("Executando localmente")
    st.code(body="streamlit run index.py", language="shell")

    st.divider()

    st.subheader("Repositório do projeto")
    st.markdown(f"""
    [![GitHub](https://img.shields.io/badge/GitHub-Repo-blue?logo=github)](https://github.com/MichaelJourdain93/Datathon_Passos_Magicos)
    """, unsafe_allow_html=True)

pg = st.navigation(pages, expanded=False)

pg.run()
