# -*- coding: utf-8 -*-
"""conclusao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10L75nwjr0hjwmSNVWkAB9PQIqdkXSWEW
"""

pip install streamlit

import streamlit as st

st.title('**Conclusão**')
st.subheader('**Insights sobre o Impacto da ONG Passos Mágicos**')
st.write(""" A análise abrangente dos dados da ONG Passos Mágicos revela um impacto multifacetado e positivo na vida dos estudantes atendidos, com insights importantes sobre o programa e seus resultados. """)

st.subheader('**Foco e Desafios**')
st.write(""" A ONG concentra seu atendimento em estudantes nas fases iniciais de sua trajetória educacional, com maior número de alunos entre 11 e 13 anos. Apesar do sucesso nesse público, há um desafio de aumentar a retenção e o acompanhamento dos alunos nas fases mais avançadas, especialmente a partir dos 16 anos, onde se observa maior evasão ou menor participação.""")
st.write(""" A análise da defasagem educacional revela que alunos mais jovens (10-15 anos) apresentam um avanço em relação à fase ideal para sua idade, enquanto alunos mais velhos (a partir de 18 anos) demonstram atraso. A transição crítica entre 16 e 17 anos marca a mudança entre alunos adiantados e atrasados, evidenciando a necessidade de intervenções específicas para reduzir a defasagem nas idades mais avançadas. """)

st.subheader('**Indicadores de Desempenho**')
st.write(""" **Correlação positiva entre indicadores:** Os dados revelam uma forte correlação positiva entre o Indicador de Desenvolvimento Educacional (INDE) e o Indicador de Desempenho Acadêmico (IDA), indicando que o desenvolvimento educacional está associado a melhores desempenhos acadêmicos.""")
st.write(""" **Engajamento como fator chave:** O Indicador de Engajamento (IEG) se destaca como um fator crucial para o sucesso dos alunos, com forte correlação com o INDE e o IDA. Isso sugere que o engajamento é fundamental para o desenvolvimento educacional e o desempenho acadêmico. """)
st.write(""" **Outros indicadores relevantes:** Além do INDE, IDA e IEG, o Indicador de Ponto de Virada (IPV) também se mostra relevante, representando momentos críticos no progresso dos alunos. """)

st.subheader('**Desempenho por Disciplina e Nível**')
st.write(""" **Notas e desempenho:** As notas em Matemática, Português e Inglês apresentam medianas semelhantes, com destaque para Inglês. No entanto, todas as disciplinas têm outliers significativos em notas muito baixas, indicando que alguns alunos enfrentam dificuldades específicas. """)
st.write(""" **Amplitude das notas:** A amplitude das notas é maior em Matemática e Português do que em Inglês, sugerindo que essas disciplinas podem apresentar maiores desafios para alguns alunos. """)
st.write(""" **Desempenho por tipo de instituição:** Alunos de instituições privadas com programas de bolsas apresentam IDA mais alto em comparação com escolas públicas ou redes convencionais, evidenciando o impacto positivo de iniciativas direcionadas. """)

st.subheader('**Insights Adicionais**')
st.write(""" **Diversidade de atendimento:** A ONG atende alunos de diferentes gêneros e fases, mostrando a amplitude do programa e seu impacto na vida dos estudantes. """)
st.write(""" **Evolução ao longo do tempo:** O INDE apresentou um crescimento constante até o início de 2023, seguido por uma queda gradual, indicando a necessidade de monitorar e ajustar o programa para garantir o desenvolvimento educacional contínuo dos alunos. """)
st.write(""" **Impacto do programa:** A análise demonstra que a ONG Passos Mágicos tem um impacto positivo significativo na vida dos estudantes atendidos, melhorando o desempenho acadêmico, promovendo o engajamento e o desenvolvimento pessoal dos alunos. """)

st.subheader('**Recomendações**')
st.write(""" **Foco em alunos mais velhos:** Desenvolver estratégias específicas para aumentar a retenção e o acompanhamento de alunos nas fases mais avançadas, combatendo a evasão e a defasagem educacional.""")
st.write(""" **Intervenções direcionadas:** Implementar intervenções direcionadas para alunos com dificuldades específicas em determinadas disciplinas, como Matemática e Português. """)
st.write(""" **Fortalecer o engajamento:** Investir em iniciativas que promovam o engajamento dos alunos, reconhecendo sua importância para o desenvolvimento educacional e o desempenho acadêmico. """)
st.write(""" **Monitoramento contínuo:** Monitorar continuamente os indicadores de desempenho e ajustar o programa conforme necessário para garantir o impacto positivo na vida dos estudantes. """)

st.subheader('**Conclusão**')
st.write(""" A ONG Passos Mágicos desempenha um papel fundamental na vida de crianças e jovens, oferecendo um programa educacional abrangente que melhora o desempenho acadêmico, promove o engajamento e o desenvolvimento pessoal. Os desafios identificados, como a necessidade de maior atenção aos alunos mais velhos e a importância de fortalecer o engajamento, oferecem oportunidades para aprimorar ainda mais o impacto positivo da ONG na vida dos estudantes. """)