# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bzsot_ZT3xcWJddVucb_kt7v3KeQrBFt
"""

import streamlit as st
import streamlit.components.v1 as components

st.header('*Dashboard*')


iframe_url = "https://app.powerbi.com/view?r=eyJrIjoiZWI5MzA0NDctMTI2NC00ZWMwLTk2ZTQtZDA4MTIzNzAwNDE3IiwidCI6ImFkYWMzNzYyLWYzMWQtNDliNS1iYWI1LWY3NjcxNzZmZjQyNSJ9 "

components.iframe(iframe_url, width=1400, height=650)