# -*- coding: utf-8 -*-
"""dicionario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10L75nwjr0hjwmSNVWkAB9PQIqdkXSWEW
"""

pip install streamlit

import streamlit as st

st.title("Indicadores Educacionais")

st.write(""" **Indicador de Adequação de Nível (IAN):** Avalia se o aluno está na série correta para sua idade, medindo a defasagem entre idade e ano escolar. """)
st.write(""" **Indicador de Desempenho Acadêmico (IDA):** Mede o desempenho em disciplinas como Matemática, Português e Inglês, refletindo o progresso cognitivo do aluno. """)
st.write(""" **Indicador de Engajamento (IEG):** Avalia a participação ativa em atividades escolares e extracurriculares, crucial para o sucesso a longo prazo. """)
st.write(""" **Indicador de Autoavaliação (IAA):** Reflete a percepção do aluno sobre seu desempenho e habilidades, influenciando a autoconfiança. """)
st.write(""" **Indicador Psicossocial (IPS):** Avalia a saúde emocional e social, incluindo resiliência e interações sociais, que impactam o desempenho acadêmico. """)
st.write(""" **Indicador Psicopedagógico (IPP):** Avalia a eficácia do suporte pedagógico oferecido aos alunos. """)
st.write(""" **Indicador do Ponto de Virada (IPV):** Identifica momentos chave no desenvolvimento acadêmico ou social, como a superação de dificuldades. """)
st.write(""" **Os indicadores são divididos em:**
         **-Indicadores de Avaliação:** IAN, IDA, IEG e IAA.
         **-Indicadores de Conselho:** IPS, IPP e IPV. """)

st.subheader('**Índice de Desenvolvimento Educacional (INDE)**')
st.write("""O Índice de Desenvolvimento Educacional (INDE) é uma métrica abrangente que visa avaliar o progresso educacional de crianças e adolescentes em diferentes fases de desenvolvimento. Ele leva em consideração uma variedade de fatores que influenciam o aprendizado e o desenvolvimento, permitindo uma análise mais completa do cenário educacional. O INDE é calculado por meio de uma fórmula que pondera diferentes indicadores, cada um representando um aspecto importante do desenvolvimento educacional. Os indicadores e seus respectivos pesos variam de acordo com a fase de desenvolvimento considerada. """)
st.write(""" **Fases 0 a 7**
         Nessa fase, o INDE é composto por:
         - IAN (Indicador de Alfabetização Não): 10%
         - IDA (Indicador de Desenvolvimento da Atenção): 20%
         - IEG (Indicador de Engajamento): 20%
         - IAA (Indicador de Aprendizagem da Álgebra): 10%
         - IPS (Indicador de Percepção Social): 10%
         - IPP (Indicador de Produção Pareada): 10%
         - IPV (Indicador de Produção de Versos): 20% """)
st.write(""" **Fase 8**
         Na fase 8, a composição do INDE é ajustada para refletir as mudanças nas necessidades e habilidades dos alunos:
         -IAN (Indicador de Alfabetização Não): 10%
         - IDA (Indicador de Desenvolvimento da Atenção): 40%
         - IEG (Indicador de Engajamento): 20%
         - IAA (Indicador de Aprendizagem da Álgebra): 10%
         - IPS (Indicador de Percepção Social): 20% """)

st.subheader('**Pedra, uma classificação importante**')
st.write(""" Dentro do sistema da PEDE, os alunos também são categorizados em níveis chamados Pedra, que são: Topázio, Ametista, Ágata e Quartzo.
Os níveis de desempenho são classificados como Topázio (o mais alto) e Quartzo (o nível que indica a necessidade de maior suporte). A progressão de um aluno ao longo do tempo é refletida na mudança do seu nível de Pedra, que é calculado a partir da padronização do INDE individual dos alunos - análise relativa. Essa padronização define intervalos para melhor orientar as intervenções e análises por grupo de alunos. """)