# -*- coding: utf-8 -*-
"""introdução.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10L75nwjr0hjwmSNVWkAB9PQIqdkXSWEW
"""


import streamlit as st

st.title('**Introdução**')

tab1, tab2, tab3 = st.tabs(['O que é a Associação Passos Mágicos?', 'PEDE (Pesquisa Extensiva do Desenvolvimento Educacional)', 'O que deve ser solucionado no Datathon?'])

with tab1:
    st.subheader('**O que é a Associação Passos Mágicos?**')
    st.write("""
    A Associação Passos Mágicos, fundada por Michelle Flues e Dimetri Ivanoff, teve início em 1992, com atividades em orfanatos na cidade de Embu-Guaçu.
    Com o objetivo de mudar a vida de crianças e adolescentes de famílias de baixa renda, proporcionando-lhes melhores oportunidades.
    Em 2016, o programa foi expandido, para beneficiar um número maior de jovens, oferecendo uma fórmula mágica de transformação que inclui:
    ensino de qualidade, suporte psicológico e psicopedagógico, ampliação da visão de mundo e desenvolvimento do protagonismo.
    A partir de um programa de bolsas de estudo em escolas particulares, que abrange tanto o ensino fundamental e médio, quanto o ensino superior,
    oferecido para alunos de escolas públicas de Embu-Guaçu. Os alunos bolsistas do ensino fundamental e médio participam do Programa de Aceleração do Conhecimento,
    enquanto os universitários se mantêm conectados com a associação por meio de avaliações e ações de voluntariado.
""")

with tab2:
    st.subheader("PEDE (Pesquisa Extensiva do Desenvolvimento Educacional)")

    st.write("""
        A PEDE é uma avaliação educacional anual da Associação Passos Mágicos para monitorar o progresso de seus alunos.
        Seus principais objetivos são:
        - Avaliar o impacto da associação na vida educacional dos alunos, medindo as mudanças no desempenho ao longo do tempo.
        - Identificar áreas de aprimoramento no programa educacional, analisando os dados para melhorar as estratégias de ensino.
        - Promover a equidade, investigando a progressão dos alunos considerando seu histórico e participação nas provas, visando um ambiente educacional mais justo.
        A metodologia da PEDE combina indicadores para uma visão holística do desempenho e bem-estar dos alunos, resultando no INDE (Índice de Desenvolvimento Educacional).
        Esse índice sintetiza as dimensões de avaliação (acadêmica, psicossocial e psicopedagógica) através de indicadores de desempenho.
    """)

with tab3:
    st.subheader("O problema que deve ser solucionado no Datathon")

    st.write(""" O grande objetivo do Datathon é realizar uma proposta analítica para demonstrar o impacto que a ONG “Passos Mágicos” tem realizado sobre a comunidade que atende. E demonstrar os impactos que a ONG “Passos Mágicos” realizou sobre a performance de estudantes e levantar indicadores de performance. Criando um dashboard e storytelling contando uma história com os dados para auxiliar a Passos Mágicos a tomar as melhores decisões com base nos indicadores e conhecer o perfil dos estudantes. """)
